import { MigrationInterface, QueryRunner } from "typeorm";

export class NewMigration1763487680384 implements MigrationInterface {
    name = 'NewMigration1763487680384'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."emergency_contacts_contacttype_enum" AS ENUM('Therapist', 'Primary', 'Secondary')`);
        await queryRunner.query(`CREATE TABLE "emergency_contacts" ("id" SERIAL NOT NULL, "firstName" text NOT NULL, "lastName" text NOT NULL, "phoneNumber" text NOT NULL, "contactType" "public"."emergency_contacts_contacttype_enum" NOT NULL, "deletedAt" TIMESTAMP, "userId" integer, CONSTRAINT "PK_8be191845b6fca1c4e5ba5bd7d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reflections" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "mostDifficultToday" text NOT NULL, "mostHelpfulToday" text NOT NULL, "deletedAt" TIMESTAMP, "diary_id" integer, CONSTRAINT "REL_f59ceef5495e133bf20eb560bc" UNIQUE ("diary_id"), CONSTRAINT "PK_4154d824fef84e88b13fbe26b06" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "behaviors" ("id" SERIAL NOT NULL, "name" text NOT NULL, "deletedAt" TIMESTAMP, CONSTRAINT "UQ_fc65e4c5667f160313497a3b3ce" UNIQUE ("name"), CONSTRAINT "PK_dc34a2b981fe38b508ba9957255" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "diary_behaviors" ("diary_id" integer NOT NULL, "behavior_id" integer NOT NULL, "hasHappened" boolean NOT NULL, "deletedAt" TIMESTAMP, CONSTRAINT "PK_80071b495d2800363f91d1570eb" PRIMARY KEY ("diary_id", "behavior_id"))`);
        await queryRunner.query(`CREATE TABLE "mood_states" ("id" SERIAL NOT NULL, "name" text NOT NULL, "deletedAt" TIMESTAMP, CONSTRAINT "UQ_11cf9259108cbeefbc87c23fb22" UNIQUE ("name"), CONSTRAINT "PK_561556712716f37e395db5650d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "diary_mood_states" ("diary_id" integer NOT NULL, "mood_state_id" integer NOT NULL, "rating" integer, "deletedAt" TIMESTAMP, CONSTRAINT "PK_abc5cd08a07c8906d49616cbe8f" PRIMARY KEY ("diary_id", "mood_state_id"))`);
        await queryRunner.query(`CREATE TABLE "diaries" ("id" SERIAL NOT NULL, "entryDate" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" integer, CONSTRAINT "PK_ffd738e7d40dcfa59283dcaae87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ema_types_evaluationtype_enum" AS ENUM('rating', 'boolean')`);
        await queryRunner.query(`CREATE TABLE "ema_types" ("id" SERIAL NOT NULL, "name" text NOT NULL, "evaluationType" "public"."ema_types_evaluationtype_enum" NOT NULL, "deletedAt" TIMESTAMP, CONSTRAINT "UQ_17eb645722cc47f5febf8e660a1" UNIQUE ("name"), CONSTRAINT "PK_6488c143a0d83a2f6493b89f130" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ema_logs" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "rating" integer, "booleanValue" boolean, "logDate" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" integer, "emaTypeId" integer, CONSTRAINT "PK_5c969487668de560e89e8b411a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "skills" ("id" SERIAL NOT NULL, "name" text NOT NULL, "deletedAt" TIMESTAMP, CONSTRAINT "UQ_81f05095507fd84aa2769b4a522" UNIQUE ("name"), CONSTRAINT "PK_0d3212120f4ecedf90864d7e298" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "steps" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "description" text NOT NULL, "hasTimer" boolean NOT NULL, "requiresValidation" boolean NOT NULL, "deletedAt" TIMESTAMP, "subSkillId" integer, CONSTRAINT "PK_65f86ac8996204d11f915f66a5b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sub_skills" ("id" SERIAL NOT NULL, "name" text NOT NULL, "deletedAt" TIMESTAMP, "skillId" integer, CONSTRAINT "PK_9a524bb1e8dff2a72d39bc4929c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_skill_activities" ("id" SERIAL NOT NULL, "status" character varying NOT NULL, "effective" boolean, "rating" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" integer, "sub_skill_id" integer, CONSTRAINT "PK_c181808249508c82ff469f17e99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_gender_enum" AS ENUM('male', 'female', 'non-binary', 'other')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "firstName" text NOT NULL, "lastName" text NOT NULL, "username" text NOT NULL, "email" text NOT NULL, "password" text NOT NULL, "age" integer NOT NULL, "gender" "public"."users_gender_enum" NOT NULL, "consentAccepted" boolean NOT NULL, "deletedAt" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "daily_quotes" ("id" SERIAL NOT NULL, "quote" text NOT NULL, "day" integer NOT NULL, "deletedAt" TIMESTAMP, CONSTRAINT "PK_3ad21c39bfac31432b2c1baa0af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "auth" ("id" SERIAL NOT NULL, "accessToken" text NOT NULL, "refreshToken" text NOT NULL, "userId" integer, CONSTRAINT "REL_373ead146f110f04dad6084815" UNIQUE ("userId"), CONSTRAINT "PK_7e416cf6172bc5aec04244f6459" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "emergency_contacts" ADD CONSTRAINT "FK_9b9bb7f85035305c3dee924d222" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reflections" ADD CONSTRAINT "FK_f59ceef5495e133bf20eb560bc8" FOREIGN KEY ("diary_id") REFERENCES "diaries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "diary_behaviors" ADD CONSTRAINT "FK_032e968f7f5bf7f3d80854b38e2" FOREIGN KEY ("diary_id") REFERENCES "diaries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "diary_behaviors" ADD CONSTRAINT "FK_347f4eed7c6824c348f4641e355" FOREIGN KEY ("behavior_id") REFERENCES "behaviors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "diary_mood_states" ADD CONSTRAINT "FK_4f46f3d9e26d639bb2fcd4544b3" FOREIGN KEY ("diary_id") REFERENCES "diaries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "diary_mood_states" ADD CONSTRAINT "FK_0e4a04b0ad5c62d3fa18358fbc3" FOREIGN KEY ("mood_state_id") REFERENCES "mood_states"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "diaries" ADD CONSTRAINT "FK_6454969d8c037fee60374c8527c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ema_logs" ADD CONSTRAINT "FK_20738c981164055377474317d29" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ema_logs" ADD CONSTRAINT "FK_4fea683a757ead65ead076dc33b" FOREIGN KEY ("emaTypeId") REFERENCES "ema_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "steps" ADD CONSTRAINT "FK_78d5197c9b1d18641a9c8036b2f" FOREIGN KEY ("subSkillId") REFERENCES "sub_skills"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sub_skills" ADD CONSTRAINT "FK_d5c106757344c5f7cf146574b1e" FOREIGN KEY ("skillId") REFERENCES "skills"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_skill_activities" ADD CONSTRAINT "FK_6a0f3bdb84c18aa8c7390c7fb9b" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_skill_activities" ADD CONSTRAINT "FK_516217f6b5110fdcee4f50355df" FOREIGN KEY ("sub_skill_id") REFERENCES "sub_skills"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth" ADD CONSTRAINT "FK_373ead146f110f04dad60848154" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "auth" DROP CONSTRAINT "FK_373ead146f110f04dad60848154"`);
        await queryRunner.query(`ALTER TABLE "user_skill_activities" DROP CONSTRAINT "FK_516217f6b5110fdcee4f50355df"`);
        await queryRunner.query(`ALTER TABLE "user_skill_activities" DROP CONSTRAINT "FK_6a0f3bdb84c18aa8c7390c7fb9b"`);
        await queryRunner.query(`ALTER TABLE "sub_skills" DROP CONSTRAINT "FK_d5c106757344c5f7cf146574b1e"`);
        await queryRunner.query(`ALTER TABLE "steps" DROP CONSTRAINT "FK_78d5197c9b1d18641a9c8036b2f"`);
        await queryRunner.query(`ALTER TABLE "ema_logs" DROP CONSTRAINT "FK_4fea683a757ead65ead076dc33b"`);
        await queryRunner.query(`ALTER TABLE "ema_logs" DROP CONSTRAINT "FK_20738c981164055377474317d29"`);
        await queryRunner.query(`ALTER TABLE "diaries" DROP CONSTRAINT "FK_6454969d8c037fee60374c8527c"`);
        await queryRunner.query(`ALTER TABLE "diary_mood_states" DROP CONSTRAINT "FK_0e4a04b0ad5c62d3fa18358fbc3"`);
        await queryRunner.query(`ALTER TABLE "diary_mood_states" DROP CONSTRAINT "FK_4f46f3d9e26d639bb2fcd4544b3"`);
        await queryRunner.query(`ALTER TABLE "diary_behaviors" DROP CONSTRAINT "FK_347f4eed7c6824c348f4641e355"`);
        await queryRunner.query(`ALTER TABLE "diary_behaviors" DROP CONSTRAINT "FK_032e968f7f5bf7f3d80854b38e2"`);
        await queryRunner.query(`ALTER TABLE "reflections" DROP CONSTRAINT "FK_f59ceef5495e133bf20eb560bc8"`);
        await queryRunner.query(`ALTER TABLE "emergency_contacts" DROP CONSTRAINT "FK_9b9bb7f85035305c3dee924d222"`);
        await queryRunner.query(`DROP TABLE "auth"`);
        await queryRunner.query(`DROP TABLE "daily_quotes"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_gender_enum"`);
        await queryRunner.query(`DROP TABLE "user_skill_activities"`);
        await queryRunner.query(`DROP TABLE "sub_skills"`);
        await queryRunner.query(`DROP TABLE "steps"`);
        await queryRunner.query(`DROP TABLE "skills"`);
        await queryRunner.query(`DROP TABLE "ema_logs"`);
        await queryRunner.query(`DROP TABLE "ema_types"`);
        await queryRunner.query(`DROP TYPE "public"."ema_types_evaluationtype_enum"`);
        await queryRunner.query(`DROP TABLE "diaries"`);
        await queryRunner.query(`DROP TABLE "diary_mood_states"`);
        await queryRunner.query(`DROP TABLE "mood_states"`);
        await queryRunner.query(`DROP TABLE "diary_behaviors"`);
        await queryRunner.query(`DROP TABLE "behaviors"`);
        await queryRunner.query(`DROP TABLE "reflections"`);
        await queryRunner.query(`DROP TABLE "emergency_contacts"`);
        await queryRunner.query(`DROP TYPE "public"."emergency_contacts_contacttype_enum"`);
    }

}
